### ISSUE TITLE
feature request: add na.rm to irv()

### ISSUE THREAD

**Issue by fuhred** [ryentes/careless#14]
Any missing values will return NA for the irv score.

Ex:
```
df<-tribble(
~A,~B,~C,
1,2,3,
1,NA,3)

irv(df)
```
returns:  

`[1]  1 NA`

**Comment by ryentes** [comment]
Thanks for opening up a feature request! I don't have an issue with implementing this in the manner you describe. In general I think we should always return a vector of length n for any m x n dataframe for which we're computing an index of careless responding. If the value of the CR metric is not defined for an obs due to missing values, I think we should return an NA value for that obs.

**Comment by ryentes** [comment]
Merged fix into dev branch
